version: '3.8'

services:
  feriado-api:
    build: .
    container_name: feriado-bursatil-api
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY}
      - FERIADOS_FILE=feriados.json
      - MIN_YEAR=1900
      - MAX_YEAR_OFFSET=10
      - MAX_PROXIMOS_FERIADOS=20
      - API_PREFIX=
    volumes:
      - ./feriados.json:/app/feriados.json:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - feriado-network

networks:
  feriado-network:
    driver: bridge